puts "Admin is created"
Admin.destroy_all
Admin.create(phone_number: "23233333333",user_name:"admin",full_name:"ADMIN OF WEBSITE",location: "Pakistan",date_of_birth:"23-09-1998",email: "admin@example.com",password:"password",admin_type:0)
Page.destroy_all
puts "Page has been created"
Admin.first.pages.create(title: "Terms & Conditions", permalink: "terms&condition",content: "<h2 style='color:black;'>Welcome to housibly!</h2> </n> <p style='color:black;'> These terms and conditions outline the rules and regulations for the use of Housibly's Website, located at <a style='color:black;'>www.housibly.com.</a> </p> </n> <p style='color:black;'> By accessing this website we assume you accept these terms and conditions. Do not continue to use housibly if you do not agree to take all of the terms and conditions stated on this page. </p> </n> <p style='color:black;'> The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: <q style='color:black;'>Client</q>, <q style='color:black;'>You</q> and <q style='color:black;'>Your</q> refers to you, the person log on this website and compliant to the Company’s terms and conditions. <q style='color:black;'>The Company</q>, <q style='color:black;'>Ourselves</q>, <q style='color:black;'>We</q>, <q style='color:black;'>Our</q> and <q style='color:black;'>Us</q>, refers to our Company. <q style='color:black;'>Party</q>, <q style='color:black;'>Parties</q>, or <q style='color:black;'>Us</q>, refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken. </p>")
Admin.first.pages.create(title: "Privacy Policy", permalink: "privacy_policy",content: "<h2 style='color:black;'>Welcome to housibly!</h2> </n> </n> <p style='color:black;'> We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights. </p> </n> <h2 style='color:black;'>Please read Privacy Policy</h2> </n> <p style='color:black;'> Reservation of Rights We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it’s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions. </p> </n> <h2 style='color:black;'>Removal of links from our website</h2> </n> <p style='color:black;'> If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but . </p>")
Admin.first.pages.create(title: "FAQ", permalink: "faq",content: "<h2 style='color:black;'>Welcome to housibly!</h2> </n> <p style='color:black;'> The following organizations may link to our Website without prior written approval: </p> <ul style='color:black;'> <li style='color:black;'>Government agencies;</li> <li style='color:black;'>Search engines;</li> <li style='color:black;'>News organizations;</li> <li style='color:black;'>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site. </li> </ul style='color:black;'> </n> <p style='color:black;'> These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party’s site. </p> </n> <p style='color:black;'> We may consider and approve other link requests from the following types of organizations: </p>")
Admin.first.pages.create(title: "Job Title", permalink: "job_title",content: "<h2 style='color:black;'>Welcome to housibly (Job Title!</h2> </n> <p style='color:black;'> The following organizations may link to our Website without prior written approval: </p> <ul style='color:black;'> <li style='color:black;'>Government agencies;</li> <li style='color:black;'>Search engines;</li> <li style='color:black;'>News organizations;</li> <li style='color:black;'>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site. </li> </ul> </n> <p style='color:black;'> These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party’s site. </p> </n> <p style='color:black;'> We may consider and approve other link requests from the following types of organizations: </p>")
puts "School Pin created"
SchoolPin.create(pin_name: "New Shaheen Public School, Mianwali Qureshian, Pakistan", latitude: 28.662600,longtitude:70.395500)
SchoolPin.create(pin_name: "Little Angels Public School, Layyah, Punjab, Pakistan", latitude: 30.910986,longtitude:70.978195)
SchoolPin.create(pin_name: "Islamabad Model School for Boys, I-14, Islamabad, Pakistan", latitude:33.614288,longtitude:72.969490)
SchoolPin.create(pin_name: "Ghazali Education Trust School, Chak 427/6-R, Pakistan", latitude:29.500866,longtitude:72.916679)
SchoolPin.create(pin_name: "Aptech Computer Education, Muslim Town, Lahore, Pakistan", latitude:31.516495,longtitude:74.322845)
SchoolPin.create(pin_name: "Scarsdale International School, Lahore, Pakistan", latitude:31.463560,longtitude:74.375221)


PaperTrail::Version.all.each do |single_request|
  single_request.update(whodunnit: Admin.first.full_name)
end

